// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/keeper
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/types
package interest

import (
	"github.com/xar-network/xar-network/x/interest/internal/keeper"
	"github.com/xar-network/xar-network/x/interest/internal/types"
)

const (
	ModuleName        = types.ModuleName
	DefaultParamspace = types.DefaultParamspace
	StoreKey          = types.StoreKey
	QuerierRoute      = types.QuerierRoute
	QueryInterest     = types.QueryInterest
)

var (
	// functions aliases
	NewKeeper  = keeper.NewKeeper
	NewQuerier = keeper.NewQuerier
	//NewMinter            = types.NewMinter
	//InitialMinter        = types.InitialMinter
	//DefaultInitialMinter = types.DefaultInitialMinter
	//ValidateMinter       = types.ValidateMinter
	ParamKeyTable         = types.ParamKeyTable
	NewInterestState      = types.NewInterestState
	DefaultInterestState  = types.DefaultInterestState
	ValidateInterestState = types.ValidateInterestState
	//NewParams            = types.NewParams
	//DefaultParams        = types.DefaultParams
	//ValidateParams       = types.ValidateParams

	// variable aliases
	ModuleCdc    = types.ModuleCdc
	MinterKey    = types.MinterKey
	KeyMintDenom = types.KeyMintDenom
)

type (
	Keeper         = keeper.Keeper
	InterestState  = types.InterestState
	InterestAsset  = types.InterestAsset
	InterestAssets = types.InterestAssets
)
